import type { Candidate } from './types';

export const candidates: Candidate[] = [
  {
    id: 'benhur-abalos',
    fullName: 'Benjamin "Benhur" Abalos Jr.',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-7',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'bam-aquino',
    fullName: 'Paolo Benigno "Bam" Aquino IV',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-8',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'abby-binay',
    fullName: 'Mar-len Abigail "Abby" Binay',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-9',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'pia-cayetano',
    fullName: 'Pia Cayetano',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-10',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'ronald-dela-rosa',
    fullName: 'Ronald "Bato" Dela Rosa',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-11',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'christopher-go',
    fullName: 'Christopher "Bong" Go',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-12',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'ping-lacson',
    fullName: 'Panfilo "Ping" Lacson',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-13',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'imee-marcos',
    fullName: 'Imee Marcos',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
imageUrlId: 'candidate-14',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'manny-pacquiao',
    fullName: 'Emmanuel "Manny" Pacquiao',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-15',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'tito-sotto',
    fullName: 'Vicente "Tito" Sotto III',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-16',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'ramon-revilla-jr',
    fullName: 'Ramon "Bong" Revilla Jr.',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-17',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'bonifacio-bosita',
    fullName: 'Bonifacio Bosita',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-18',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'arlene-brosas',
    fullName: 'Arlene Brosas',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-19',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'roy-cabonegro',
    fullName: 'Roy Cabonegro',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-20',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'allen-capuyan',
    fullName: 'Allen Capuyan',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-21',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'teddy-casino',
    fullName: 'Teodoro "Teddy" Casiño',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-22',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'francisca-castro',
    fullName: 'Francisca "France" Castro',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-23',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'angelo-de-alban',
    fullName: 'Angelo De Alban',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-24',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'david-dangelo',
    fullName: "David D'Angelo",
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-25',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'leody-de-guzman',
    fullName: 'Leodegario "Leody" De Guzman',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-26',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'gregorio-honasan',
    fullName: 'Gregorio "Gringo" Honasan',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-31',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'relly-jose-jr',
    fullName: 'Relly Jose Jr.',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-32',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'raul-lambino',
    fullName: 'Raul Lambino',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-34',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'manuel-lapid',
    fullName: 'Manuel "Lito" Lapid',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-35',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'wilbert-lee',
    fullName: 'Wilbert Lee',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-36',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'amirah-lidasan',
    fullName: 'Amirah Lidasan',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-37',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'rodante-marcoleta',
    fullName: 'Rodante Marcoleta',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-38',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'norman-marquez',
    fullName: 'Norman Marquez',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-40',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'eric-martinez',
    fullName: 'Eric Martinez',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-41',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'richard-mata',
    fullName: 'Richard Mata',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-42',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'jose-matula',
    fullName: 'Jose "Sonny" Gito Matula',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-43',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'liza-maza',
    fullName: 'Liza Largoza Maza',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-44',
    education: [],
careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'heidi-mendoza',
    fullName: 'Heidi Lloce Mendoza',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-45',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'jose-montemayor-jr',
    fullName: 'Jose Jr. Cabrera Montemayor',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-46',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'jose-jessei-olivar',
    fullName: 'Jose Jessei Dela Calsada Olivar',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-47',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'willie-ong',
    fullName: 'Willie Tan Ong',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-48',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'kiko-pangilinan',
    fullName: 'Francis "Kiko" Pangilinan',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-50',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'ariel-querubin',
    fullName: 'Ariel Porfirio Oliva Querubin',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-51',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'apollo-quiboloy',
    fullName: 'Apollo Carreon Quiboloy',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-52',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'danilo-ramos',
    fullName: 'Danilo Hernandez Ramos',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-53',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'willie-revillame',
    fullName: 'Wilfredo "Willie" Revillame',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-54',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'vic-rodriguez',
    fullName: 'Victor "Vic" Rodriguez',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-55',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'nur-ana-sahidulla',
    fullName: 'Nur-Ana Indanan Sahidulla',
    positionSought: 'Senator',
politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-56',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'phillip-salvador',
    fullName: 'Phillip Reyes Salvador',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-57',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'chavit-singson',
    fullName: 'Luis "Chavit" Singson',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-58',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  }
];
