import type { Candidate } from './types';

export const candidates: Candidate[] = [
  {
    id: 'gabriela-silang',
    fullName: 'Gabriela Silang',
    positionSought: 'Senator',
    politicalAffiliation: 'Lakas ng Kababaihan',
    imageUrlId: 'candidate-4',
    education: [
      {
        degree: 'Bachelor of Science in Community Development',
        institution: 'University of the Philippines Los Baños',
        year: '2005',
        source: { label: 'UPLB Registrar', url: '#' },
      },
    ],
    careerTimeline: [
      {
        date: '2013-2022',
        title: 'Party-list Representative',
        description: 'Represented the women\'s sector, authoring bills on gender equality and rural development.',
        isMilestone: true,
        source: { label: 'Congress.gov.ph', url: '#' },
      },
      {
        date: '2006-2012',
        title: 'Community Organizer',
        description: 'Worked with various NGOs focusing on women\'s rights and empowerment.',
        isMilestone: false,
        source: { label: 'NGO Network Records', url: '#' },
      },
    ],
    platforms: [
      {
        title: 'Women\'s Economic Empowerment',
        description: 'Pushes for laws that provide greater economic opportunities for women, including access to capital and training.',
        source: { label: 'Campaign Website', url: '#' },
      },
    ],
    controversies: [],
    promises: [
      {
        promise: 'To establish a national hotline and support system for victims of domestic violence.',
        relatedActions: [
          {
            description: 'Filed a bill in 2019 to create a national domestic violence support system, which reached a second reading.',
            source: { label: 'House Bill No. 5432', url: '#' }
          }
        ]
      }
    ]
  },
  {
    id: 'benhur-abalos',
    fullName: 'Benjamin "Benhur" Abalos Jr.',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-7',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'bam-aquino',
    fullName: 'Paolo Benigno "Bam" Aquino IV',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-8',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'abby-binay',
    fullName: 'Mar-len Abigail "Abby" Binay',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-9',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'pia-cayetano',
    fullName: 'Pia Cayetano',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-10',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'ronald-dela-rosa',
    fullName: 'Ronald "Bato" Dela Rosa',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-11',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'christopher-go',
    fullName: 'Christopher "Bong" Go',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-12',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'ping-lacson',
    fullName: 'Panfilo "Ping" Lacson',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-13',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'imee-marcos',
    fullName: 'Imee Marcos',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-14',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'manny-pacquiao',
    fullName: 'Emmanuel "Manny" Pacquiao',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-15',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'tito-sotto',
    fullName: 'Vicente "Tito" Sotto III',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-16',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'ramon-revilla-jr',
    fullName: 'Ramon "Bong" Revilla Jr.',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-17',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'bonifacio-bosita',
    fullName: 'Bonifacio Bosita',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-18',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'arlene-brosas',
    fullName: 'Arlene Brosas',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-19',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'roy-cabonegro',
    fullName: 'Roy Cabonegro',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-20',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'allen-capuyan',
    fullName: 'Allen Capuyan',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-21',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'teddy-casino',
    fullName: 'Teodoro "Teddy" Casiño',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-22',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'francisca-castro',
    fullName: 'Francisca "France" Castro',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-23',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'angelo-de-alban',
    fullName: 'Angelo De Alban',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-24',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'david-dangelo',
    fullName: "David D'Angelo",
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-25',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'leody-de-guzman',
    fullName: 'Leodegario "Leody" De Guzman',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-26',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'gregorio-honasan',
    fullName: 'Gregorio "Gringo" Honasan',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-31',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'relly-jose-jr',
    fullName: 'Relly Jose Jr.',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-32',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'raul-lambino',
    fullName: 'Raul Lambino',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-34',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'manuel-lapid',
    fullName: 'Manuel "Lito" Lapid',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-35',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'wilbert-lee',
    fullName: 'Wilbert Lee',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-36',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'amirah-lidasan',
    fullName: 'Amirah Lidasan',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-37',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'rodante-marcoleta',
    fullName: 'Rodante Marcoleta',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-38',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'norman-marquez',
    fullName: 'Norman Marquez',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-40',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'eric-martinez',
    fullName: 'Eric Martinez',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-41',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'richard-mata',
    fullName: 'Richard Mata',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-42',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'jose-matula',
    fullName: 'Jose "Sonny" Gito Matula',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-43',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'liza-maza',
    fullName: 'Liza Largoza Maza',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-44',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'heidi-mendoza',
    fullName: 'Heidi Lloce Mendoza',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-45',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'jose-montemayor-jr',
    fullName: 'Jose Jr. Cabrera Montemayor',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-46',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'jose-jessei-olivar',
    fullName: 'Jose Jessei Dela Calsada Olivar',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-47',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'willie-ong',
    fullName: 'Willie Tan Ong',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-48',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'kiko-pangilinan',
    fullName: 'Francis "Kiko" Pangilinan',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-50',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'ariel-querubin',
    fullName: 'Ariel Porfirio Oliva Querubin',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-51',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'apollo-quiboloy',
    fullName: 'Apollo Carreon Quiboloy',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-52',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'danilo-ramos',
    fullName: 'Danilo Hernandez Ramos',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: 'candidate-53',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  }
];

export const literacyTopics = [
  {
    id: 'role-comelec',
    title: 'What is the role of COMELEC?',
    content: 'The Commission on Elections (COMELEC) is the principal government agency tasked by the Constitution to enforce and administer all laws and regulations concerning the conduct of regular and special elections. Its primary role is to ensure free, orderly, honest, peaceful, and credible elections.',
  },
  {
    id: 'powers-executive',
    title: 'What are the powers of the President and Vice President?',
    content: 'The President is the head of state and government, and serves as the commander-in-chief of the Armed Forces. Key powers include executing laws, appointing officials, and conducting foreign policy. The Vice President\'s main role is to succeed the President in case of death, disability, or resignation. They may also be appointed to a cabinet position by the President.',
  },
  {
    id: 'how-elections-work',
    title: 'How do Philippine national elections work?',
    content: 'National elections are held every six years. Voters cast their ballots for President, Vice President, Senators, and local officials. The Philippines uses an automated election system, where votes are cast on ballots, fed into vote-counting machines, and electronically transmitted for canvassing.',
  },
  {
    id: 'read-records',
    title: 'How do I read a candidate\'s record critically?',
    content: 'When evaluating a candidate, look for consistency between their promises and past actions. Check the sources of information—are they from official government sites, reputable news organizations, or court records? Be aware of the difference between allegations and proven facts. A long track record in public service can provide more data points for evaluation.',
  },
];
